site_name: Info-Maths
site_url: https://info-maths.netlify.app/
site_author: David Couronné
site_description: >-
  Informatique (NSI - SNT) et Mathématiques au lycée de Cornouaille

# Repository
repo_name: davidcouronne/info-maths
repo_url: https://github.com/davidcouronne/info-maths
edit_uri: edit/main/docs/


# Configuration
theme:
  name: material
  language: fr
  features:
    # - announce.dismiss
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    # - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css

extra:
  analytics:
    provider: google
    property: G-RWG1VRBX8Z
  consent:
    title: Les Cookies
    description: >- 
      Nous utilisons des cookies pour reconnaître vos visites répétées et vos préférences, ainsi que
      pour mesurer l'efficacité de notre site et si les utilisateurs
      trouver ce qu'ils recherchent. Avec votre consentement, vous nous aidez à
      améliorer notre documentation.


plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - glightbox
  - social


markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true 
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

# Page tree
nav:
  - Accueil: index.md
  - Ressources:
    - Anaconda et Miniconda: ressources/conda.md
    - Visual Studio Code: ressources/vscode.md
    - Types en Python: ressources/types.md
  - Terminale NSI:
    - Introduction: terminales/index.md
    - Sujets écrits:
      - terminales/sujets-ecrits/index.md
      - Sujets complets: terminales/sujets-ecrits/02-sujets.md
      - Sujets structures: terminales/sujets-ecrits/03-structures.md
      - Sujets SQL: terminales/sujets-ecrits/04-bases-donnees.md
      - Sujets architecture: terminales/sujets-ecrits/05-architecture.md
      - Sujets langages: terminales/sujets-ecrits/06-langages.md
      - Sujets algo: terminales/sujets-ecrits/07-algorithmique.md
    - Sujets pratiques:
      - terminales/sujets_pratiques/index.md 
      - Sujet 1: terminales/sujets_pratiques/sujet1.md    
      - Sujet 2: terminales/sujets_pratiques/sujet2.md  
      - Sujet 3: terminales/sujets_pratiques/sujet3.md 
      - Sujet 4: terminales/sujets_pratiques/sujet4.md  
      - Sujet 11: terminales/sujets_pratiques/sujet11.md
      - Sujet 23: terminales/sujets_pratiques/sujet23.md